language: python
python:
  - "2.7"
  - "3.6"
  - "3.6-dev"
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - echo "running-- conda env create -f conda/environment.yml -n testenv python=$TRAVIS_PYTHON_VERSION"
  - conda env create -q -f conda/environment.yml -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install pip
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install 'PyScaffold==2.5' 
    else
      pip install 'PyScaffold==2.5'
    fi
  - python setup.py install

script:
  - python setup.py test
