name: nlpiaenv

channels:
  - conda-forge
  - defaults

dependencies:
  - boto3>=1.9.3,<1.10.0
  - gensim>=3.4.0,<3.5.0
  - jupyter>=1.0.0,<2.0.0
  - keras>=2.2.2,<2.3.0
  - keras-applications>=1.0.4,<1.1.0
  - keras-preprocessing>=1.0.2,<1.1.0
  - matplotlib>=2.2.2,<2.3.0
  - nltk>=3.2.5,<3.3.0
  - numpy>=1.15.1,<1.17.0
  - opencv>=3.3.0,<3.6.0
  - pandas>=0.23.4,<0.25.0
  - pandoc>=2.1.3,<2.2.0
  - pillow>=4.3.0,<4.4.0
  - pip>=17.0
  - plac>=0.9.6,<0.10.0
  - plotly>=3.1.1,<3.2.0
  - pyqt>=5.6,<5.7
  - python-levenshtein>=0.12.0,<0.13.0
  - redis-py>=2.10.6
  - spacy>=2.0.12,<2.1.0
  - swig>=3.0.12,<3.1.0
  - tensorflow>=1.10.0,<1.11.0

  - pip:
    - -r ../requirements/requirements-base.txt
