name: nlpiaenv

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - botocore
  - cython==0.29
  - gensim>=3.4.0,<3.7.0
  - h5py==2.8.0
  - html5lib==1.1
  - jupyter==1.0.0
  - keras-applications>=1.0.6
  - keras-preprocessing>=1.0.5
  - keras==2.2.4
  - matplotlib==3.2.2
  - mechanicalsoup
  - nltk>=3.4.5,<3.5.0
  - opencv>=3.3.0,<3.5.0
  - pandas==0.25.3
  - pandoc>=2.2.3,<3.0.0
  - pip>=18.0
  - plac>=0.9.6,<1.0.0
  - plotly==3.3.0
  - pyscaffold>=3.1
  - pytest-cov
  - python-levenshtein>=0.12.0,<0.13.0
  - redis-py>=2.10.6
  - scipy==1.1.0
  - spacy==2.0.18
  - swig>=3.0.12
  - tensorflow-hub==0.4.0
  - theano>=1.0.2
  # this will fail on windows:
  # - python-annoy>=1.9.5,<2.0.0

  - pip:
    - -r ../requirements/requirements-base.txt
